/**
 * Recommendation Repository - Database access layer for recommendations and feedback tables
 * Strategic Layer Phase 4: Recommendation Engine
 *
 * Provides CRUD operations and query functions for recommendations generated by the engine.
 * Also manages feedback for learning from user decisions.
 */

import { query } from '../../db.js';
import { randomUUID } from 'crypto';

// ============================================
// TypeScript Types
// ============================================

/**
 * Recommendation types for classification
 */
export type RecommendationType = 'action' | 'optimization' | 'warning' | 'opportunity';

/**
 * Priority levels
 */
export type RecommendationPriority = 'critical' | 'high' | 'medium' | 'low';

/**
 * Status of a recommendation
 */
export type RecommendationStatus = 'pending' | 'accepted' | 'rejected' | 'deferred' | 'expired';

/**
 * Row type matching PostgreSQL recommendations table structure
 */
export interface RecommendationRow {
  id: string;
  title: string;
  description: string;
  recommendation_type: RecommendationType;
  priority: RecommendationPriority;
  source_pattern_ids: string[];
  related_goal_ids: string[];
  suggested_intent: string;
  confidence: number;
  status: RecommendationStatus;
  accepted_at: Date | null;
  rejected_at: Date | null;
  deferred_until: Date | null;
  feedback_id: string | null;
  created_at: Date;
  updated_at: Date;
  expires_at: Date | null;
}

/**
 * Input for creating a new recommendation
 */
export interface RecommendationInput {
  title: string;
  description: string;
  recommendationType: RecommendationType;
  priority: RecommendationPriority;
  sourcePatternIds: string[];
  relatedGoalIds: string[];
  suggestedIntent: string;
  confidence: number;
  expiresAt?: Date;
}

/**
 * Query options for filtering recommendations
 */
export interface RecommendationQueryOptions {
  status?: RecommendationStatus | RecommendationStatus[];
  priority?: RecommendationPriority | RecommendationPriority[];
  type?: RecommendationType | RecommendationType[];
  sourcePatternId?: string;
  relatedGoalId?: string;
  minConfidence?: number;
  limit?: number;
  offset?: number;
  orderBy?: 'created_at' | 'priority' | 'confidence' | 'expires_at';
  orderDir?: 'ASC' | 'DESC';
}

/**
 * Statistics about recommendations
 */
export interface RecommendationStats {
  total: number;
  byStatus: Record<string, number>;
  byPriority: Record<string, number>;
  byType: Record<string, number>;
  avgConfidence: number | null;
  acceptanceRate: number | null;
  pendingCount: number;
  expiringInNext24h: number;
}

/**
 * Row type for feedback table
 */
export interface FeedbackRow {
  id: string;
  entity_type: 'recommendation' | 'pattern' | 'goal';
  entity_id: string;
  action: 'accept' | 'reject' | 'defer';
  feedback_text: string | null;
  feedback_rating: number | null;
  created_by: string;
  created_at: Date;
}

/**
 * Input for creating feedback
 */
export interface FeedbackInput {
  entityType: 'recommendation' | 'pattern' | 'goal';
  entityId: string;
  action: 'accept' | 'reject' | 'defer';
  feedbackText?: string;
  feedbackRating?: number;
  createdBy?: string;
}

// ============================================
// Recommendation CRUD Functions
// ============================================

/**
 * Insert a new recommendation into the recommendations table
 * Returns the inserted row or null on failure
 */
export async function insertRecommendation(input: RecommendationInput): Promise<RecommendationRow | null> {
  const id = randomUUID();
  const now = new Date();
  // Default expiry is 7 days from now
  const expiresAt = input.expiresAt || new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

  try {
    const result = await query<RecommendationRow>(
      `INSERT INTO recommendations
        (id, title, description, recommendation_type, priority, source_pattern_ids, related_goal_ids,
         suggested_intent, confidence, status, created_at, updated_at, expires_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending', $10, $11, $12)
       RETURNING *`,
      [
        id,
        input.title,
        input.description,
        input.recommendationType,
        input.priority,
        input.sourcePatternIds,
        input.relatedGoalIds,
        input.suggestedIntent,
        input.confidence,
        now,
        now,
        expiresAt,
      ]
    );

    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Inserted recommendation ${result.rows[0].id}: ${input.title}`);
      return result.rows[0];
    }
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to insert recommendation:', error);
    return null;
  }
}

/**
 * Retrieve a single recommendation by UUID
 * Returns null if not found
 */
export async function getRecommendationById(id: string): Promise<RecommendationRow | null> {
  try {
    const result = await query<RecommendationRow>(
      `SELECT * FROM recommendations WHERE id = $1`,
      [id]
    );

    return result.rows.length > 0 ? result.rows[0] : null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get recommendation by ID:', error);
    return null;
  }
}

/**
 * Flexible query with filters and pagination
 * Default limit 50, ordered by created_at DESC
 */
export async function queryRecommendations(options: RecommendationQueryOptions = {}): Promise<RecommendationRow[]> {
  const {
    status,
    priority,
    type,
    sourcePatternId,
    relatedGoalId,
    minConfidence,
    limit = 50,
    offset = 0,
    orderBy = 'created_at',
    orderDir = 'DESC',
  } = options;

  const conditions: string[] = [];
  const params: unknown[] = [];
  let paramIndex = 1;

  // Build dynamic WHERE clauses
  if (status) {
    if (Array.isArray(status)) {
      conditions.push(`status = ANY($${paramIndex}::text[])`);
      params.push(status);
    } else {
      conditions.push(`status = $${paramIndex}`);
      params.push(status);
    }
    paramIndex++;
  }

  if (priority) {
    if (Array.isArray(priority)) {
      conditions.push(`priority = ANY($${paramIndex}::text[])`);
      params.push(priority);
    } else {
      conditions.push(`priority = $${paramIndex}`);
      params.push(priority);
    }
    paramIndex++;
  }

  if (type) {
    if (Array.isArray(type)) {
      conditions.push(`recommendation_type = ANY($${paramIndex}::text[])`);
      params.push(type);
    } else {
      conditions.push(`recommendation_type = $${paramIndex}`);
      params.push(type);
    }
    paramIndex++;
  }

  if (sourcePatternId) {
    conditions.push(`$${paramIndex} = ANY(source_pattern_ids)`);
    params.push(sourcePatternId);
    paramIndex++;
  }

  if (relatedGoalId) {
    conditions.push(`$${paramIndex} = ANY(related_goal_ids)`);
    params.push(relatedGoalId);
    paramIndex++;
  }

  if (minConfidence !== undefined) {
    conditions.push(`confidence >= $${paramIndex}`);
    params.push(minConfidence);
    paramIndex++;
  }

  // Build WHERE clause
  const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';

  // Validate order columns to prevent SQL injection
  const validOrderBy = ['created_at', 'priority', 'confidence', 'expires_at'].includes(orderBy)
    ? orderBy
    : 'created_at';
  const validOrderDir = ['ASC', 'DESC'].includes(orderDir.toUpperCase()) ? orderDir.toUpperCase() : 'DESC';

  // Special handling for priority ordering (need custom order)
  let orderClause: string;
  if (validOrderBy === 'priority') {
    orderClause = `ORDER BY CASE priority
      WHEN 'critical' THEN 1
      WHEN 'high' THEN 2
      WHEN 'medium' THEN 3
      WHEN 'low' THEN 4
      END ${validOrderDir}`;
  } else {
    orderClause = `ORDER BY ${validOrderBy} ${validOrderDir}`;
  }

  // Add limit and offset
  params.push(limit);
  params.push(offset);

  const sql = `
    SELECT * FROM recommendations
    ${whereClause}
    ${orderClause}
    LIMIT $${paramIndex} OFFSET $${paramIndex + 1}
  `;

  try {
    const result = await query<RecommendationRow>(sql, params);
    return result.rows;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to query recommendations:', error);
    return [];
  }
}

/**
 * Get pending recommendations ordered by priority then creation date
 */
export async function getPendingRecommendations(limit: number = 50): Promise<RecommendationRow[]> {
  return queryRecommendations({
    status: 'pending',
    limit,
    orderBy: 'priority',
    orderDir: 'ASC', // critical first
  });
}

/**
 * Get recommendations expiring within the given hours
 */
export async function getExpiringRecommendations(withinHours: number = 24): Promise<RecommendationRow[]> {
  const threshold = new Date(Date.now() + withinHours * 60 * 60 * 1000);

  try {
    const result = await query<RecommendationRow>(
      `SELECT * FROM recommendations
       WHERE status = 'pending'
       AND expires_at IS NOT NULL
       AND expires_at <= $1
       ORDER BY expires_at ASC`,
      [threshold]
    );
    return result.rows;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get expiring recommendations:', error);
    return [];
  }
}

/**
 * Update an existing recommendation
 * Returns updated row or null if not found
 */
export async function updateRecommendation(
  id: string,
  updates: Partial<{
    title: string;
    description: string;
    recommendationType: RecommendationType;
    priority: RecommendationPriority;
    sourcePatternIds: string[];
    relatedGoalIds: string[];
    suggestedIntent: string;
    confidence: number;
    expiresAt: Date | null;
  }>
): Promise<RecommendationRow | null> {
  const existing = await getRecommendationById(id);
  if (!existing) {
    return null;
  }

  const now = new Date();
  const fields: string[] = ['updated_at = $1'];
  const params: unknown[] = [now];
  let paramIndex = 2;

  if (updates.title !== undefined) {
    fields.push(`title = $${paramIndex}`);
    params.push(updates.title);
    paramIndex++;
  }

  if (updates.description !== undefined) {
    fields.push(`description = $${paramIndex}`);
    params.push(updates.description);
    paramIndex++;
  }

  if (updates.recommendationType !== undefined) {
    fields.push(`recommendation_type = $${paramIndex}`);
    params.push(updates.recommendationType);
    paramIndex++;
  }

  if (updates.priority !== undefined) {
    fields.push(`priority = $${paramIndex}`);
    params.push(updates.priority);
    paramIndex++;
  }

  if (updates.sourcePatternIds !== undefined) {
    fields.push(`source_pattern_ids = $${paramIndex}`);
    params.push(updates.sourcePatternIds);
    paramIndex++;
  }

  if (updates.relatedGoalIds !== undefined) {
    fields.push(`related_goal_ids = $${paramIndex}`);
    params.push(updates.relatedGoalIds);
    paramIndex++;
  }

  if (updates.suggestedIntent !== undefined) {
    fields.push(`suggested_intent = $${paramIndex}`);
    params.push(updates.suggestedIntent);
    paramIndex++;
  }

  if (updates.confidence !== undefined) {
    fields.push(`confidence = $${paramIndex}`);
    params.push(updates.confidence);
    paramIndex++;
  }

  if (updates.expiresAt !== undefined) {
    fields.push(`expires_at = $${paramIndex}`);
    params.push(updates.expiresAt);
    paramIndex++;
  }

  params.push(id);

  const sql = `
    UPDATE recommendations
    SET ${fields.join(', ')}
    WHERE id = $${paramIndex}
    RETURNING *
  `;

  try {
    const result = await query<RecommendationRow>(sql, params);
    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Updated recommendation ${id}`);
      return result.rows[0];
    }
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to update recommendation:', error);
    return null;
  }
}

// ============================================
// Status Update Functions
// ============================================

/**
 * Accept a recommendation
 * Sets status to accepted and accepted_at timestamp
 */
export async function acceptRecommendation(id: string, feedbackId?: string): Promise<RecommendationRow | null> {
  const now = new Date();

  try {
    const result = await query<RecommendationRow>(
      `UPDATE recommendations
       SET status = 'accepted', accepted_at = $1, feedback_id = $2, updated_at = $3
       WHERE id = $4 AND status = 'pending'
       RETURNING *`,
      [now, feedbackId || null, now, id]
    );

    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Accepted recommendation ${id}`);
      return result.rows[0];
    }
    console.warn(`[RecommendationRepo] Could not accept recommendation ${id} - not found or not pending`);
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to accept recommendation:', error);
    return null;
  }
}

/**
 * Reject a recommendation
 * Sets status to rejected and rejected_at timestamp
 */
export async function rejectRecommendation(id: string, feedbackId?: string): Promise<RecommendationRow | null> {
  const now = new Date();

  try {
    const result = await query<RecommendationRow>(
      `UPDATE recommendations
       SET status = 'rejected', rejected_at = $1, feedback_id = $2, updated_at = $3
       WHERE id = $4 AND status = 'pending'
       RETURNING *`,
      [now, feedbackId || null, now, id]
    );

    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Rejected recommendation ${id}`);
      return result.rows[0];
    }
    console.warn(`[RecommendationRepo] Could not reject recommendation ${id} - not found or not pending`);
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to reject recommendation:', error);
    return null;
  }
}

/**
 * Defer a recommendation until a specified date
 * Sets status to deferred and deferred_until timestamp
 */
export async function deferRecommendation(id: string, deferUntil: Date, feedbackId?: string): Promise<RecommendationRow | null> {
  const now = new Date();

  try {
    const result = await query<RecommendationRow>(
      `UPDATE recommendations
       SET status = 'deferred', deferred_until = $1, feedback_id = $2, updated_at = $3
       WHERE id = $4 AND status = 'pending'
       RETURNING *`,
      [deferUntil, feedbackId || null, now, id]
    );

    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Deferred recommendation ${id} until ${deferUntil.toISOString()}`);
      return result.rows[0];
    }
    console.warn(`[RecommendationRepo] Could not defer recommendation ${id} - not found or not pending`);
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to defer recommendation:', error);
    return null;
  }
}

/**
 * Expire old pending recommendations
 * Returns count of expired recommendations
 */
export async function expireOldRecommendations(): Promise<number> {
  const now = new Date();

  try {
    const result = await query(
      `UPDATE recommendations
       SET status = 'expired', updated_at = $1
       WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at < $1`,
      [now]
    );

    const count = result.rowCount || 0;
    if (count > 0) {
      console.log(`[RecommendationRepo] Expired ${count} recommendations`);
    }
    return count;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to expire recommendations:', error);
    return 0;
  }
}

/**
 * Reactivate deferred recommendations that have passed their defer date
 * Changes status back to pending
 */
export async function reactivateDeferredRecommendations(): Promise<number> {
  const now = new Date();

  try {
    const result = await query(
      `UPDATE recommendations
       SET status = 'pending', deferred_until = NULL, updated_at = $1
       WHERE status = 'deferred' AND deferred_until IS NOT NULL AND deferred_until <= $1`,
      [now]
    );

    const count = result.rowCount || 0;
    if (count > 0) {
      console.log(`[RecommendationRepo] Reactivated ${count} deferred recommendations`);
    }
    return count;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to reactivate deferred recommendations:', error);
    return 0;
  }
}

// ============================================
// Statistics Functions
// ============================================

/**
 * Get aggregate statistics for dashboard/monitoring
 */
export async function getRecommendationStats(): Promise<RecommendationStats> {
  try {
    // Get basic stats
    const basicResult = await query<{
      total: string;
      avg_confidence: string | null;
      pending_count: string;
    }>(
      `SELECT
        COUNT(*) as total,
        AVG(confidence) as avg_confidence,
        COUNT(*) FILTER (WHERE status = 'pending') as pending_count
       FROM recommendations`
    );

    // Get counts by status
    const statusResult = await query<{ status: string; count: string }>(
      `SELECT status, COUNT(*) as count
       FROM recommendations
       GROUP BY status`
    );

    // Get counts by priority
    const priorityResult = await query<{ priority: string; count: string }>(
      `SELECT priority, COUNT(*) as count
       FROM recommendations
       GROUP BY priority`
    );

    // Get counts by type
    const typeResult = await query<{ recommendation_type: string; count: string }>(
      `SELECT recommendation_type, COUNT(*) as count
       FROM recommendations
       GROUP BY recommendation_type`
    );

    // Get acceptance rate
    const rateResult = await query<{
      total_decided: string;
      accepted: string;
    }>(
      `SELECT
        COUNT(*) FILTER (WHERE status IN ('accepted', 'rejected')) as total_decided,
        COUNT(*) FILTER (WHERE status = 'accepted') as accepted
       FROM recommendations`
    );

    // Get expiring in next 24h
    const expiringResult = await query<{ count: string }>(
      `SELECT COUNT(*) as count
       FROM recommendations
       WHERE status = 'pending'
       AND expires_at IS NOT NULL
       AND expires_at <= NOW() + INTERVAL '24 hours'`
    );

    const basic = basicResult.rows[0] || {};
    const rate = rateResult.rows[0] || {};
    const expiring = expiringResult.rows[0] || {};

    const byStatus: Record<string, number> = {};
    for (const row of statusResult.rows) {
      byStatus[row.status] = parseInt(row.count, 10);
    }

    const byPriority: Record<string, number> = {};
    for (const row of priorityResult.rows) {
      byPriority[row.priority] = parseInt(row.count, 10);
    }

    const byType: Record<string, number> = {};
    for (const row of typeResult.rows) {
      byType[row.recommendation_type] = parseInt(row.count, 10);
    }

    const totalDecided = parseInt(rate.total_decided || '0', 10);
    const accepted = parseInt(rate.accepted || '0', 10);
    const acceptanceRate = totalDecided > 0 ? accepted / totalDecided : null;

    return {
      total: parseInt(basic.total || '0', 10),
      byStatus,
      byPriority,
      byType,
      avgConfidence: basic.avg_confidence ? parseFloat(basic.avg_confidence) : null,
      acceptanceRate,
      pendingCount: parseInt(basic.pending_count || '0', 10),
      expiringInNext24h: parseInt(expiring.count || '0', 10),
    };
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get recommendation stats:', error);
    return {
      total: 0,
      byStatus: {},
      byPriority: {},
      byType: {},
      avgConfidence: null,
      acceptanceRate: null,
      pendingCount: 0,
      expiringInNext24h: 0,
    };
  }
}

/**
 * Count recommendations by source pattern
 */
export async function countRecommendationsByPattern(patternId: string): Promise<number> {
  try {
    const result = await query<{ count: string }>(
      `SELECT COUNT(*) as count FROM recommendations WHERE $1 = ANY(source_pattern_ids)`,
      [patternId]
    );

    return parseInt(result.rows[0]?.count || '0', 10);
  } catch (error) {
    console.error('[RecommendationRepo] Failed to count recommendations by pattern:', error);
    return 0;
  }
}

/**
 * Count recommendations by related goal
 */
export async function countRecommendationsByGoal(goalId: string): Promise<number> {
  try {
    const result = await query<{ count: string }>(
      `SELECT COUNT(*) as count FROM recommendations WHERE $1 = ANY(related_goal_ids)`,
      [goalId]
    );

    return parseInt(result.rows[0]?.count || '0', 10);
  } catch (error) {
    console.error('[RecommendationRepo] Failed to count recommendations by goal:', error);
    return 0;
  }
}

// ============================================
// Feedback Functions
// ============================================

/**
 * Insert feedback for an entity
 */
export async function insertFeedback(input: FeedbackInput): Promise<FeedbackRow | null> {
  const id = randomUUID();

  try {
    const result = await query<FeedbackRow>(
      `INSERT INTO feedback
        (id, entity_type, entity_id, action, feedback_text, feedback_rating, created_by, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
       RETURNING *`,
      [
        id,
        input.entityType,
        input.entityId,
        input.action,
        input.feedbackText || null,
        input.feedbackRating || null,
        input.createdBy || 'brian',
      ]
    );

    if (result.rows.length > 0) {
      console.log(`[RecommendationRepo] Inserted feedback ${result.rows[0].id} for ${input.entityType} ${input.entityId}`);
      return result.rows[0];
    }
    return null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to insert feedback:', error);
    return null;
  }
}

/**
 * Get feedback by ID
 */
export async function getFeedbackById(id: string): Promise<FeedbackRow | null> {
  try {
    const result = await query<FeedbackRow>(
      `SELECT * FROM feedback WHERE id = $1`,
      [id]
    );

    return result.rows.length > 0 ? result.rows[0] : null;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get feedback by ID:', error);
    return null;
  }
}

/**
 * Get all feedback for an entity
 */
export async function getFeedbackForEntity(entityType: string, entityId: string): Promise<FeedbackRow[]> {
  try {
    const result = await query<FeedbackRow>(
      `SELECT * FROM feedback
       WHERE entity_type = $1 AND entity_id = $2
       ORDER BY created_at DESC`,
      [entityType, entityId]
    );

    return result.rows;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get feedback for entity:', error);
    return [];
  }
}

/**
 * Get recent feedback (for learning in recommendation engine)
 */
export async function getRecentFeedback(limit: number = 50): Promise<FeedbackRow[]> {
  try {
    const result = await query<FeedbackRow>(
      `SELECT * FROM feedback
       ORDER BY created_at DESC
       LIMIT $1`,
      [limit]
    );

    return result.rows;
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get recent feedback:', error);
    return [];
  }
}

/**
 * Get feedback statistics (for dashboard)
 */
export async function getFeedbackStats(): Promise<{
  total: number;
  byAction: Record<string, number>;
  byEntityType: Record<string, number>;
  avgRating: number | null;
}> {
  try {
    const basicResult = await query<{ total: string; avg_rating: string | null }>(
      `SELECT COUNT(*) as total, AVG(feedback_rating) as avg_rating FROM feedback`
    );

    const actionResult = await query<{ action: string; count: string }>(
      `SELECT action, COUNT(*) as count FROM feedback GROUP BY action`
    );

    const entityResult = await query<{ entity_type: string; count: string }>(
      `SELECT entity_type, COUNT(*) as count FROM feedback GROUP BY entity_type`
    );

    const basic = basicResult.rows[0] || {};

    const byAction: Record<string, number> = {};
    for (const row of actionResult.rows) {
      byAction[row.action] = parseInt(row.count, 10);
    }

    const byEntityType: Record<string, number> = {};
    for (const row of entityResult.rows) {
      byEntityType[row.entity_type] = parseInt(row.count, 10);
    }

    return {
      total: parseInt(basic.total || '0', 10),
      byAction,
      byEntityType,
      avgRating: basic.avg_rating ? parseFloat(basic.avg_rating) : null,
    };
  } catch (error) {
    console.error('[RecommendationRepo] Failed to get feedback stats:', error);
    return {
      total: 0,
      byAction: {},
      byEntityType: {},
      avgRating: null,
    };
  }
}
